version: '3'

services:
 api:
  image: jatindemla/img_api
  container_name: my_api
  ports:
    - "9001:9001"
  environment:
    - API_SERVICE_IP=my_api:9001
    - SELECTOR_SERVICE_IP=my_selector:9002


 selector:
  image: jatindemla/img_selector
  container_name: my_selector
  ports:
    - "9002:9002"
  environment:
    - SELECTOR_SERVICE_IP=my_selector:9002
    - NOTIFIER_SERVICE_IP=my_notifier:9003

 
 notifier:  
  image: jatindemla/img_notifier
  container_name: my_notifier
  ports:
    - "9003:9003"
  environment:
    - NOTIFIER_SERVICE_IP=my_notifier:9003



